name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo mv mysh /usr/local/bin/mysh; chmod +x /usr/local/bin/mysh
    - name: Display the environment variables and their values
      run: |
        abc
      shell: mysh {0}
